runtime: python39

instance_class: F1

env_variables:
  GOOGLE_APPLICATION_CREDENTIALS: "Ajay_application_default_credentials.json"

entrypoint: python main.py

handlers:
- url: /.*
  script: auto

automatic_scaling:
  target_cpu_utilization: 0.65
  min_instances: 1
  max_instances: 5